apiVersion: v1
kind: Service
metadata:
  name: assessment-app-service
  namespace: assessment
spec:
  type: LoadBalancer
  selector:
    app: assessment-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000